# Generated by Django 3.2 on 2023-06-13 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('crtime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('msgs', models.TextField(blank=True, null=True, verbose_name='消息内容')),
                ('foruser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '消息列表',
                'verbose_name_plural': '消息列表',
                'ordering': ['-crtime'],
            },
        ),
    ]
